---
- hosts: travis
  connection: local
  vars:
    executable: "{{ ansible_env.HOME }}/.go/bin/ghq"
  roles:
  - role: suzuki-shunsuke.go
  post_tasks:
  - name: Install ghq
    go:
      name: github.com/motemen/ghq
      executable: /usr/local/go/bin/go
      gopath: "{{ ansible_env.HOME }}/.go"
  - name: Clone suzuki-shunsuke/zsh.conf
    ghq:
      name: suzuki-shunsuke/zsh.conf
      executable: "{{ executable }}"
  - name: Update
    ghq:
      name: suzuki-shunsuke/zsh.conf
      executable: "{{ executable }}"
      update: yes
  - name: Specify the ghq.root
    ghq:
      name: suzuki-shunsuke/vim.conf
      executable: "{{ executable }}"
      root: "{{ ansible_env.HOME }}/repos"
  - name: Validation Test
    ghq:
      executable: "{{ executable }}"
      src: repos.txt
      name: suzuki-shunsuke/tmux.conf
    register: result
    failed_when: "not result.failed"
  - name: Shallow Clone
    ghq:
      name: suzuki-shunsuke/tmux.conf
      executable: "{{ executable }}"
      shallow: yes
- hosts: localhost
  connection: local
  vars:
    executable: "{{ ansible_env.HOME }}/.go/bin/ghq"
  roles:
  - ghq
